# Generated by Django 5.2.8 on 2025-11-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notified_10min',
            field=models.BooleanField(default=False),
        ),
    ]
